import React from "react";
import { Select } from "./Select";

const LANGUAGES = [
	{ id: "english", name: "English" },
	{ id: "chinese", name: "Chinese" },
	{ id: "german", name: "German" },
	{ id: "spanish", name: "Spanish" },
	{ id: "russian", name: "Russian" },
	{ id: "korean", name: "Korean" },
	{ id: "french", name: "French" },
	{ id: "japanese", name: "Japanese" },
	{ id: "portuguese", name: "Portuguese" },
	{ id: "turkish", name: "Turkish" },
	{ id: "polish", name: "Polish" },
	{ id: "catalan", name: "Catalan" },
	{ id: "dutch", name: "Dutch" },
	{ id: "arabic", name: "Arabic" },
	{ id: "swedish", name: "Swedish" },
	{ id: "italian", name: "Italian" },
	{ id: "indonesian", name: "Indonesian" },
	{ id: "hindi", name: "Hindi" },
	{ id: "finnish", name: "Finnish" },
	{ id: "vietnamese", name: "Vietnamese" },
	{ id: "hebrew", name: "Hebrew" },
	{ id: "ukrainian", name: "Ukrainian" },
	{ id: "greek", name: "Greek" },
	{ id: "malay", name: "Malay" },
	{ id: "czech", name: "Czech" },
	{ id: "romanian", name: "Romanian" },
	{ id: "danish", name: "Danish" },
	{ id: "hungarian", name: "Hungarian" },
	{ id: "tamil", name: "Tamil" },
	{ id: "norwegian", name: "Norwegian" },
	{ id: "thai", name: "Thai" },
	{ id: "urdu", name: "Urdu" },
	{ id: "croatian", name: "Croatian" },
	{ id: "bulgarian", name: "Bulgarian" },
	{ id: "lithuanian", name: "Lithuanian" },
	{ id: "latin", name: "Latin" },
	{ id: "maori", name: "Maori" },
	{ id: "malayalam", name: "Malayalam" },
	{ id: "welsh", name: "Welsh" },
	{ id: "slovak", name: "Slovak" },
	{ id: "telugu", name: "Telugu" },
	{ id: "persian", name: "Persian" },
	{ id: "latvian", name: "Latvian" },
	{ id: "bengali", name: "Bengali" },
	{ id: "serbian", name: "Serbian" },
	{ id: "azerbaijani", name: "Azerbaijani" },
	{ id: "slovenian", name: "Slovenian" },
	{ id: "kannada", name: "Kannada" },
	{ id: "estonian", name: "Estonian" },
	{ id: "macedonian", name: "Macedonian" },
	{ id: "breton", name: "Breton" },
	{ id: "basque", name: "Basque" },
	{ id: "icelandic", name: "Icelandic" },
	{ id: "armenian", name: "Armenian" },
	{ id: "nepali", name: "Nepali" },
	{ id: "mongolian", name: "Mongolian" },
	{ id: "bosnian", name: "Bosnian" },
	{ id: "kazakh", name: "Kazakh" },
	{ id: "albanian", name: "Albanian" },
	{ id: "swahili", name: "Swahili" },
	{ id: "galician", name: "Galician" },
	{ id: "marathi", name: "Marathi" },
	{ id: "punjabi", name: "Punjabi" },
	{ id: "sinhala", name: "Sinhala" },
	{ id: "khmer", name: "Khmer" },
	{ id: "shona", name: "Shona" },
	{ id: "yoruba", name: "Yoruba" },
	{ id: "somali", name: "Somali" },
	{ id: "afrikaans", name: "Afrikaans" },
	{ id: "occitan", name: "Occitan" },
	{ id: "georgian", name: "Georgian" },
	{ id: "belarusian", name: "Belarusian" },
	{ id: "tajik", name: "Tajik" },
	{ id: "sindhi", name: "Sindhi" },
	{ id: "gujarati", name: "Gujarati" },
	{ id: "amharic", name: "Amharic" },
	{ id: "yiddish", name: "Yiddish" },
	{ id: "lao", name: "Lao" },
	{ id: "uzbek", name: "Uzbek" },
	{ id: "faroese", name: "Faroese" },
	{ id: "haitian creole", name: "Haitian Creole" },
	{ id: "pashto", name: "Pashto" },
	{ id: "turkmen", name: "Turkmen" },
	{ id: "nynorsk", name: "Nynorsk" },
	{ id: "maltese", name: "Maltese" },
	{ id: "sanskrit", name: "Sanskrit" },
	{ id: "luxembourgish", name: "Luxembourgish" },
	{ id: "myanmar", name: "Myanmar" },
	{ id: "tibetan", name: "Tibetan" },
	{ id: "tagalog", name: "Tagalog" },
	{ id: "malagasy", name: "Malagasy" },
	{ id: "assamese", name: "Assamese" },
	{ id: "tatar", name: "Tatar" },
	{ id: "hawaiian", name: "Hawaiian" },
	{ id: "lingala", name: "Lingala" },
	{ id: "hausa", name: "Hausa" },
	{ id: "bashkir", name: "Bashkir" },
	{ id: "javanese", name: "Javanese" },
	{ id: "sundanese", name: "Sundanese" },
	{ id: "cantonese", name: "Cantonese" },
];

export const LANGUAGE_IDS = LANGUAGES.map((l) => l.id);

export function formatTranscriptionLanguageId(languageId: string): string {
	return LANGUAGES.find((l) => l.id === languageId)?.name ?? languageId;
}

export type TranscriptionLanguageSelectProps = {
	value: string;
	onChange: (value: string) => void;
	supportedLanguageIds: string[];
};

export const TranscriptionLanguageSelect = React.memo((props: TranscriptionLanguageSelectProps) => {
	const options = LANGUAGES.filter((l) => props.supportedLanguageIds.includes(l.id)).map((l) => ({
		value: l.id,
		label: l.name,
	}));
	return <Select onChange={props.onChange} options={options} value={props.value} />;
});
